network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:  # Replace with your actual interface name
      addresses:
        - 192.168.0.5/24  # Controller IP (change to 192.168.0.6 for compute)
      gateway4: 192.168.0.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      dhcp4: false

# Alternative configuration for DHCP with static assignment:
# network:
#   version: 2
#   renderer: networkd
#   ethernets:
#     eth0:
#       dhcp4: true
#       dhcp4-overrides:
#         hostname: controller  # or compute1 for compute node

# To apply configuration:
# sudo netplan apply

# To test configuration:
# sudo netplan try
